#!/bin/bash
COMMON=`dirname $0`/common

if [ ! -f "$COMMON" ] ; then
  error "'$COMMON' not found."
elif [ ! -r "$COMMON" ] ; then
  error "'$COMMON' not readable."
else
  . $COMMON
fi

echo -ne "Checking if $LVMVOLUME is mounted..."

checkmount $SNAPSHOTMOUNT
rc=$?
if [ $rc -eq 1 ]; then
  echo "Yes...Aborting"
  error "Volume is mounted. Please unmount and re-run."
else
  echo "No"
fi

echo -ne "Checking availability of Volume '$LVMVOLUME'..."

lvdisplay $LVMVOLUME > /dev/null
rc=$?
if [ $rc -ne 0 ]; then
  echo "Not available"
  error "Volume '$LVMVOLUME' does not exist."
fi

echo "OK"

echo "Creating LVM snapshot at $LVMPATH/$LVMSNAPSHOT..."
lvcreate -L $SNAPSHOTSIZE -s -n $LVMSNAPSHOT $LVMVOLUME
rc=$?
if [ $rc -eq 0 ]; then
  echo "Snapshot created successfully"
  echo
  echo "Mounting LVM snapshot for backup..."  

  if [ -d $SNAPSHOTMOUNT ]; then
    echo "  Mount directory exists, ommiting mkdir..."
  else
    echo -ne "  Creating mount directory at $SNAPSHOTMOUNT..."
    mkdir -p $SNAPSHOTMOUNT
    if [ $rc -eq 0 ]; then
      echo "OK"
    else
      echo "Error"
      error "Error on creating mount directory"
    fi    
  fi
  
  mount $LVMPATH/$LVMSNAPSHOT $SNAPSHOTMOUNT
  rc=$?
  if [ $rc -ne 0 ]; then
    lvremove -f $LVMPATH/$LVMSNAPSHOT
    error "Error on mounting LVM snapshot"
  fi
  echo "Snapshot mounted successfully"
else
  error "Error on creating LVM snapshot"
fi
